### ISSUE TITLE
sd/sd_twizy_interface.sh

### ISSUE THREAD

**Issue by LukePhairatt** [streetdrone-home/SD-VehicleInterface#1]
#!/bin/bash
sudo modprobe peak_usb

sudo ip link set can0 up type can bitrate 500000

# ==== probably we don't need ? ===
sudo ip link set can0 up 
# ===========================

source ../../../devel/setup.bash

roslaunch sd sd_twizy_interface.launch

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Yes thank you for your input, it was duplication on bringing can interface up. 
Changed it to:
```
sudo ip link set can0 type can bitrate 500000
sudo ip link set can0 up
````
