### ISSUE TITLE
sd_twizy_interface_node.cpp - subscribe frame rate 8000

### ISSUE THREAD

**Issue by LukePhairatt** [streetdrone-home/SD-VehicleInterface#2]
It is a bit much? This might starve the cpu? Would it work at 200 hz the same as publisher.
int subscribe_rate = 8000;

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
When running the subscriber on the same rate as the publisher there is a large delay on the /received_messages topic. The messages from the subscriber arrived approx 3.5 seconds later than the publisher. This affected the performance of the PID as the vehicle's velocity input from the CAN bus was not updating as frequently as expected. 
To solve this issue we chose to run the subscriber on a second thread with different rate and after testing on the car and comparing the logged XCU can frame rates we concluded that 8000 was the optimal rate for reducing the publisher/subscriber delay.
