### ISSUE TITLE
sd_twizy_interface_node.cpp - Twist angular

### ISSUE THREAD

**Issue by LukePhairatt** [streetdrone-home/SD-VehicleInterface#4]
twist_angular = 57.296 * twist_angular;

Why do you multiply 57.296? Where is this number coming from?

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
We multiply with 57.296 to convert Radians/Sec to Degrees/Sec
We do this to later on calculate the low lever steer command for the SD Twizy.
