### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by LukePhairatt** [streetdrone-home/SD-VehicleInterface#6]
Limitations:
Speed control with closed loop feedback, limited to 10 mps
# Is it 10 meters/sec or 10 miles/hour?

Angular acceleration requests without feedback loop, limited to 100 deg/s
# Angular speed, Not Angular acceleration?

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
* 10 mps - it's meters per second
* It is angular speed not angular acceleration you are right
