### ISSUE TITLE
Transferred CAN frame latency issue

### ISSUE THREAD

**Issue by HHF111** [streetdrone-home/SD-VehicleInterface#8]
Do you have any issue with unstable sample rate of sent out can frames?

**Comment by FionanOSullivan-StreetDrone** [comment]
Hi there, 
Could you be a little more specific about the issue please? What behavior have you encountered? 

The XCU embedded system expects CAN comms at 200Hz (min). It's reasonably tolerant to a small amount of jitter, but will handback to manual mode if the can comms accumulate errors, or if doesn't receive a fresh frame within a small time tolerance. 

If you're encountering issues here, try raising the frequency a small amount by increasing ROS_LOOP to 250 or so. You can keep the same control rate by also increasing CONTROL_LOOP to the same ratio, i.e 25. 

I hope that helps, 
Fionan

**Comment by FionanOSullivan-StreetDrone** [comment]
Closed due to inaction
